### ISSUE TITLE
Support DNS Primary Servers

### ISSUE THREAD

**Issue by jkroepke** [acim/hcdns#9]
https://dns.hetzner.com/api-docs#operation/GetPrimaryServers

**Comment by acim** [comment]
Could you maybe contribute this? If not I will do it, but I can't promise when it is going to be finished.

**Comment by acim** [comment]
I started working on this: https://github.com/acim/hcdns/tree/feature/primary-servers

**Comment by acim** [comment]
One method is implemented but I have no time for others at this moment. Since no one else asked for this, I will just close this.
